# Generated by Django 5.2 on 2025-05-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_available_copies_book_numberofcopies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
